version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: notilttoday1/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: notilttoday1/kittygram_frontend
    env_file: .env 
    command: cp -r /app/build/. /static/ # Еще нужна команда сбора статики?
    volumes:
      - static:/static
  gateway:
    image: notilttoday1/kittygram_gateway
    env_file: .env
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 9000 хоста
    # на порт 80 контейнера.
    # А тут подключаем volume со статикой к gateway
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
